### ISSUE TITLE
Error during heroku setup

### ISSUE THREAD

**Issue by klamping** [diffux/diffux#127]
I ran into an error when going through the steps for the Heroku set up and wanted to include what I did that seemed to fix it:

Error: When running `heroku run rake db:migrate`, I get this error: 

```
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "all"
: SELECT  "projects".* FROM "projects"  WHERE "projects"."id" = $1 LIMIT 1
rake aborted!
```

To fix, I ran `heroku run rake db:setup`. Then I ran the previous command and things worked (at least as far as I can tell).

I mention it as I don't really know much about getting this all set up, so I'm not sure this is the correct solution, but it did seem to work for me.

**Comment by klamping** [comment]
Well, doesn't look like that solved it (or maybe there's another issue). I can create project successfully now, but when I run a sweep the snapshots never return.

**Comment by trotzig** [comment]
Just a couple of quick question: 
Have you made sure to setup an Amaxon S3 account? 
Is there anything in the logs that looks interesting?

Sorry for not being able to provide more help. I haven't used Heroku for running Diffux in quite some time.

**Comment by klamping** [comment]
Thanks for getting back. No worries on the outdated docs, I know how that goes.

I did add the keys for the S3 account, but i never verified that they were working properly.

Right now I'm attempting to get Vagrantfile set up for DiffUX that does automatic provisioning/installation of the right dependencies. We'll see how that goes.

**Comment by tdooner** [comment]
Hey @klamping, I just tried setting up Diffux on Heroku again (it's been at least 6 months since I originally wrote the instructions). The instructions were a bit out-of-date (fixed in #131) and the migrations appear to be broken (fixed in #130). With those fixes you should consider giving it another shot :).

**Comment by klamping** [comment]
Going to try it out right now :) (assuming my kids stay asleep)

**Comment by klamping** [comment]
I was able to get it installed w/o trouble, but am still having issues getting the screenshots to render. I believe I set up the AWS credentials right, but is there a good way to validate or test out what's happening?

**Comment by klamping** [comment]
Nevermind, figured out I can look at the logs. Looks like S3 is giving me "access denied" errors. Will look in to this and see what I can find.
